# Generated by Django 6.0.2 on 2026-02-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='property_images/')),
                ('three_d_file', models.FileField(blank=True, null=True, upload_to='3d_models/')),
                ('description', models.TextField()),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('area', models.CharField(default='1200 sqft', max_length=50)),
            ],
        ),
    ]
