# Generated by Django 6.0.2 on 2026-02-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='interior_file',
            field=models.FileField(blank=True, null=True, upload_to='3d_models/interiors/'),
        ),
    ]
