# Generated by Django 6.0.2 on 2026-03-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_listedproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedproperty',
            name='location_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='location_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='interactive_mesh_names',
            field=models.TextField(blank=True, default='', help_text='Comma-separated mesh names. Example: Geom3D106, Geom3D022, Geom3D050'),
        ),
    ]
