# Generated by Django 6.0.2 on 2026-03-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_property_audio_tour_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedproperty',
            name='builder',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='builder',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
